#!/system/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Generated by build_cache_probe.py. Includes Apache-2.0 AOSP AIDL clients.
# Creates/configures/reads/deletes ONLY a newly acquired resolver cache (1000000).
# No netd network, routes, app bindings, global DNS settings or DNS queries.
# Run: /system/bin/sh /sdcard/Download/dnscheck-v3.sh

PATH=/system/bin:/system/xbin:/vendor/bin:/product/bin
export PATH
unset LD_PRELOAD LD_LIBRARY_PATH
umask 077
if [ "$(/system/bin/id -u)" != 0 ]; then
  echo 'Сначала введи su и разреши root, затем повтори запуск скрипта.'
  exit 1
fi
if [ ! -x /system/bin/timeout ]; then
  echo 'Нет /system/bin/timeout. Проверка не запущена.'
  exit 1
fi
zdns_report=/sdcard/Download/dnsprofiles-report-v3.txt
exec 3>&1
if ! : > "$zdns_report"; then
  echo "Не удалось создать $zdns_report"
  exit 1
fi
exec > "$zdns_report" 2>&1
echo 'ZDT-D DNS Resolver isolated cache check v3.1 (dynamic output arrays)'
echo 'No app is assigned to the test cache; active DNS configuration is not replaced.'
/system/bin/id
/system/bin/getprop ro.build.version.sdk
/system/bin/getenforce
zdns_status=1
zdns_temp=$(/system/bin/mktemp -d /data/local/tmp/zdtd-dnscheck.XXXXXX)
if [ -n "$zdns_temp" ] && [ -d "$zdns_temp" ]; then
  cleanup() {
    /system/bin/rm -f "$zdns_temp/probe.dex"
    /system/bin/rmdir "$zdns_temp" 2>/dev/null
  }
  trap cleanup EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM HUP
  if /system/bin/base64 -d > "$zdns_temp/probe.dex" <<'ZDNS_DEX'
@@DEX_BASE64@@
ZDNS_DEX
  then
    zdns_sum=$(/system/bin/sha256sum "$zdns_temp/probe.dex")
    zdns_sum=${zdns_sum%% *}
    if [ "$zdns_sum" = '@@DEX_SHA256@@' ]; then
      /system/bin/chmod 400 "$zdns_temp/probe.dex"
      printf 'Проверяю запись и чтение отдельного тестового кэша DNS…\n' >&3
      # Keep stdout/stderr pipe-backed for Binder; never pass the report FD.
      zdns_output=$(/system/bin/timeout 60 /system/bin/env CLASSPATH="$zdns_temp/probe.dex" \
        /system/bin/app_process /system/bin DnsResolverCacheProbe --cache-selftest </dev/null 2>&1)
      zdns_status=$?
      printf '%s\nexit_code=%s\n' "$zdns_output" "$zdns_status"
    else
      echo 'RESULT=FAIL; DEX checksum mismatch'
    fi
  else
    echo 'RESULT=FAIL; cannot decode DEX'
  fi
else
  echo 'RESULT=FAIL; cannot create private temporary directory'
fi
if [ "$zdns_status" = 0 ]; then
  printf 'Проверка прошла. DNS по приложениям ещё не включён.\n' >&3
else
  printf 'Проверка не прошла; причина записана в отчёт.\n' >&3
  case "$zdns_output" in
    *cache_destroyed=1000000*) echo 'Cleanup: destroyNetworkCache returned successfully.' ;;
    *cache_created=1000000*) echo 'Cleanup unconfirmed; keep this report. Do not blindly destroy an existing cache.' ;;
    *) echo 'No confirmed cache creation; see operation error above.' ;;
  esac
fi
printf '\nПришли файл:\n%s\n' "$zdns_report" >&3
exit "$zdns_status"

# Complete probe and AIDL source, provenance and licenses follow as comments.
@@SOURCE_COMMENTS@@
