#!/system/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Read-only Android DNS capability probe. Generated by build_probe.py.
# Run from a root shell: /system/bin/sh /sdcard/Download/dnscheck-v2.sh
# Writes a report and a temporary private DEX; does not change DNS or routes.

zdns_original_cmd=$(command -v cmd 2>/dev/null)
zdns_su=$(command -v su 2>/dev/null)
PATH=/system/bin:/system/xbin:/vendor/bin:/product/bin
export PATH
unset LD_PRELOAD LD_LIBRARY_PATH
umask 077

if [ "$(/system/bin/id -u)" != 0 ]; then
  echo 'Сначала введи su и разреши root, затем повтори запуск скрипта.'
  exit 1
fi
if [ ! -x /system/bin/timeout ]; then
  echo 'Нет /system/bin/timeout. Проверка не запущена.'
  exit 1
fi
zdns_report=/sdcard/Download/dnsprofiles-report-v2.txt
exec 3>&1
if ! : > "$zdns_report"; then
  echo "Не удалось создать $zdns_report"
  exit 1
fi
exec > "$zdns_report" 2>&1

check() {
  printf '\n[%s]\n' "$1"
  printf 'Проверка: %s\n' "$1" >&3
  shift
  # Binder shell commands receive pipe-backed stdout/stderr, never the report
  # file. stdin uses /dev/null, not a Termux terminal descriptor.
  zdns_output=$(/system/bin/timeout 12 "$@" </dev/null 2>&1)
  zdns_status=$?
  printf '%s\nexit_code=%s\n' "$zdns_output" "$zdns_status"
  return "$zdns_status"
}

echo 'ZDT-D DNS capability report v2; network configuration is unchanged'
printf 'original_cmd=%s\n' "$zdns_original_cmd"
echo 'stdout_transport=pipe; stdin=/dev/null; executables=system'
check root_context /system/bin/id
check android_sdk /system/bin/getprop ro.build.version.sdk
check selinux /system/bin/getenforce
check private_dns_mode_root /system/bin/settings get global private_dns_mode
check youtube_uid_root /system/bin/cmd package list packages -U com.google.android.youtube
check chrome_uid_root /system/bin/cmd package list packages -U com.android.chrome
if [ -n "$zdns_su" ] && [ -x "$zdns_su" ]; then
  # Same supported shell-user invocation already used by ZDT-D's UID resolver.
  # A failure is recorded; no permission/SELinux settings are changed.
  if check shell_user "$zdns_su" -lp 2000 -c '/system/bin/id'; then
    check private_dns_mode_shell "$zdns_su" -lp 2000 -c '/system/bin/settings get global private_dns_mode'
    check youtube_uid_shell "$zdns_su" -lp 2000 -c '/system/bin/cmd package list packages -U com.google.android.youtube'
    check chrome_uid_shell "$zdns_su" -lp 2000 -c '/system/bin/cmd package list packages -U com.android.chrome'
  fi
fi
check resolver_service /system/bin/service check dnsresolver
check netd_service /system/bin/service check netd
check legacy_resolver /system/bin/ndc resolver
check resolver_shell_help /system/bin/cmd dnsresolver help

zdns_temp=$(/system/bin/mktemp -d /data/local/tmp/zdtd-dnscheck.XXXXXX)
if [ -n "$zdns_temp" ] && [ -d "$zdns_temp" ]; then
  cleanup() {
    /system/bin/rm -f "$zdns_temp/probe.dex"
    /system/bin/rmdir "$zdns_temp" 2>/dev/null
  }
  trap cleanup EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM HUP
  if /system/bin/base64 -d > "$zdns_temp/probe.dex" <<'ZDNS_DEX'
@@DEX_BASE64@@
ZDNS_DEX
  then
    zdns_sum=$(/system/bin/sha256sum "$zdns_temp/probe.dex")
    zdns_sum=${zdns_sum%% *}
    if [ "$zdns_sum" = '@@DEX_SHA256@@' ]; then
      /system/bin/chmod 400 "$zdns_temp/probe.dex"
      check resolver_binder_probe /system/bin/env CLASSPATH="$zdns_temp/probe.dex" \
        /system/bin/app_process /system/bin DnsResolverProbe
    else
      echo 'resolver_binder_probe=SKIPPED; DEX checksum mismatch'
    fi
  else
    echo 'resolver_binder_probe=SKIPPED; cannot decode DEX'
  fi
else
  echo 'resolver_binder_probe=SKIPPED; cannot create private temporary directory'
fi
echo
echo 'Report complete. Capabilities only; DNS isolation and setter permissions are not verified.'
printf '\nГотово. Пришли файл:\n%s\n' "$zdns_report" >&3

# The exact source of the embedded probe follows for review.
@@JAVA_SOURCE_COMMENTS@@
